spring:
  datasource:
    hikari:
      connection-timeout: 600000
      iddle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
    url: jdbc:postgresql://127.0.0.1/book_catalog
    username: subrutin
    password: password
  jpa:
    database: POSTGRESQL
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8081

app:
  welcome-text: "Hello World, kuyylah"
  timezone: "Asia/Jakarta"
  currency: "IDR"

cloud:
  api-key: thisiskey


---
spring:
  profile: development

server:
  port: 8003

app:
  welcome-text: Hello World, kuyylah, this is for development



