server:
  port: 8081

app:
  welcome-text: "Hello World, kuyylah"
  timezone: "Asia/Jakarta"
  currency: "IDR"

cloud:
  api-key: thisiskey


---
spring:
  profile: development

server:
  port: 8003

app:
  welcome-text: Hello World, kuyylah, this is for development



